language: java
script: mvn clean verify -Pjacoco coveralls:report
# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2
notifications:
   # Email notifications are disabled
   email: false
deploy:
-  provider: script
   skip_cleanup: true
   script: bash bintray.sh
   on:
      branch: master
